version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: wldigital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Extreme123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:Extreme123@db:5432/wldigital
    depends_on:
      - db

volumes:
  postgres_data: